language: python
python:
 - "3.6"

script:
 - python test_calculator.py

 deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: test-my-travisci-project
  on:
    repo: StevenChu-ccp/SoftwareEng